// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VenueSync.Data;

#nullable disable

namespace VenueSync.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260317122021_UpdateVenueImages")]
    partial class UpdateVenueImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VenueSync.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("EventId");

                    b.HasIndex("VenueId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("VenueSync.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("VenueSync.Models.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("VenueId");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            VenueId = 1,
                            Capacity = 250,
                            Description = "A warm and welcoming church hall featuring a bright interior, high ceilings, and a peaceful atmosphere. Ideal for weddings, community gatherings, meetings, and small celebrations, offering a comfortable and serene setting for meaningful events.",
                            ImageUrl = "https://images.unsplash.com/photo-1677051286670-1e83ec52d87e?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y2h1cmNoJTIwaGFsbHxlbnwwfHwwfHx8MA%3D%3D",
                            Location = "12 Unity Street, Johannesburg",
                            VenueName = "St. Mary's Church Hall"
                        },
                        new
                        {
                            VenueId = 2,
                            Capacity = 50000,
                            Description = "A massive open-air stadium designed for large-scale concerts, sporting events, and festivals. Featuring state-of-the-art lighting, sound systems, and expansive seating, it provides an electrifying atmosphere for unforgettable live experiences.",
                            ImageUrl = "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8c3RhZGl1bXxlbnwwfHwwfHx8MA%3D%3D",
                            Location = "120 Arena Drive, Durban",
                            VenueName = "Metro Grand Stadium"
                        },
                        new
                        {
                            VenueId = 3,
                            Capacity = 800,
                            Description = "A beautiful open-air city park surrounded by greenery and skyline views, ideal for outdoor events, picnics, festivals, and community gatherings. The venue offers a relaxed and natural atmosphere with plenty of space for creative and flexible event setups.",
                            ImageUrl = "https://images.unsplash.com/photo-1696079196661-a5cbfb884255?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8Y2l0eSUyMHBhcmt8ZW58MHx8MHx8fDA%3D",
                            Location = "78 Park Lane, Pretoria",
                            VenueName = "Greenfield City Park"
                        });
                });

            modelBuilder.Entity("VenueSync.Models.Booking", b =>
                {
                    b.HasOne("VenueSync.Models.Event", "Event")
                        .WithMany("Bookings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VenueSync.Models.Venue", "Venue")
                        .WithMany("Bookings")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("VenueSync.Models.Event", b =>
                {
                    b.HasOne("VenueSync.Models.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("VenueSync.Models.Event", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("VenueSync.Models.Venue", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
